### ISSUE TITLE
No orbs in Wikipedia Mobile view

### ISSUE THREAD

**Issue by todrobbins** [derenrich/wwwyzzerdd#10]
![Screen Shot 2021-11-18 at 4 58 05 PM](https://user-images.githubusercontent.com/158590/142515483-db19c119-99af-4692-ae2d-6b88c5fde0bb.png)

I'm not sure if this was an intentional design decision, but the orbs are missing when viewing `en.m.wikipedia.org` URLs. I imagine this has something to do with a difference in classes/IDs. I prefer reading articles in mobile view on desktop and it'd be nice to still be able to contribute to WD with this really useful extension in that view.

Cheers!

**Comment by derenrich** [comment]
It wasn't originally designed for mobile devices and I kinda assumed nobody used mobile on desktop. But it's a pretty simple matter to make that work. It's fixed in https://github.com/derenrich/wwwyzzerdd/commit/fab3de9aa1a2df1023aba286b0fd7434a7901b43 and it'll be in the next release (version 0.0.2.8 or higher).

**Comment by todrobbins** [comment]
Well thank you for considering my use case! Again, such a great tool!
